# Generated by Django 5.2.1 on 2025-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('subject', models.CharField(choices=[('inquiry', 'General Inquiry'), ('support', 'Customer Support'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], max_length=20, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('position', models.CharField(choices=[('sales', 'Sales Associate'), ('customer-service', 'Customer Service'), ('warehouse', 'Warehouse Staff'), ('management', 'Management'), ('other', 'Other')], max_length=20, verbose_name='Position of Interest')),
                ('experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=10, verbose_name='Years of Experience')),
                ('resume', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Resume')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Cover Letter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Employment Application',
                'verbose_name_plural': 'Employment Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
